// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.0 (Build Build 614 04/24/2018)
// Created on Fri Apr 08 15:13:59 2022

filter filter_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.clk_enable(clk_enable_sig) ,	// input  clk_enable_sig
	.reset(reset_sig) ,	// input  reset_sig
	.filter_in(filter_in_sig) ,	// input [31:0] filter_in_sig
	.filter_out(filter_out_sig) 	// output [15:0] filter_out_sig
);

defparam filter_inst.coeff1 = 'b0000001110111111;
defparam filter_inst.coeff2 = 'b0000111000111101;
defparam filter_inst.coeff3 = 'b0010000111101010;
defparam filter_inst.coeff4 = 'b0011110010010001;
defparam filter_inst.coeff5 = 'b0101011011101111;
defparam filter_inst.coeff6 = 'b0110011101111100;
defparam filter_inst.coeff7 = 'b0110011101111100;
defparam filter_inst.coeff8 = 'b0101011011101111;
defparam filter_inst.coeff9 = 'b0011110010010001;
defparam filter_inst.coeff10 = 'b0010000111101010;
defparam filter_inst.coeff11 = 'b0000111000111101;
defparam filter_inst.coeff12 = 'b0000001110111111;
