// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.0 (Build Build 614 04/24/2018)
// Created on Sat Apr 09 10:11:33 2022

MODE MODE_inst
(
	.clk_100M(clk_100M_sig) ,	// input  clk_100M_sig
	.rst_n(rst_n_sig) ,	// input  rst_n_sig
	.mode(mode_sig) ,	// input [2:0] mode_sig
	.sin_sig(sin_sig_sig) ,	// input [15:0] sin_sig_sig
	.AM_sig(AM_sig_sig) ,	// input [15:0] AM_sig_sig
	.FM_sig(FM_sig_sig) ,	// input [15:0] FM_sig_sig
	.AM_De_sig(AM_De_sig_sig) ,	// input [15:0] AM_De_sig_sig
	.FM_De_sig(FM_De_sig_sig) ,	// input [15:0] FM_De_sig_sig
	.sig_out(sig_out_sig) 	// output [15:0] sig_out_sig
);

