// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.0 (Build Build 614 04/24/2018)
// Created on Fri Apr 08 15:11:26 2022

SINCOS SINCOS_inst
(
	.clk_100M(clk_100M_sig) ,	// input  clk_100M_sig
	.rst_n(rst_n_sig) ,	// input  rst_n_sig
	.fre(fre_sig) ,	// input [23:0] fre_sig
	.SIN_sig(SIN_sig_sig) ,	// output [15:0] SIN_sig_sig
	.COS_sig(COS_sig_sig) 	// output [15:0] COS_sig_sig
);

